import type { DestinationCatalog, PlannerRules } from './types'

// Ugyanaz a 18 párizsi program + 6 zóna, mint a
// supabase/migrations/005_seed_planner_paris.sql -- ez teszi lehetővé, hogy a
// motor fejlesztői playground (/labs/planner) és a unit tesztek valós adatra
// hasonlító, de adatbázis nélküli katalógussal fussanak.

export const mockDestinationId = 'paris'

export const mockZones: DestinationCatalog['zones'] = [
  { id: 'louvre-tuileries', name: 'Louvre / Tuileries', centerLat: 48.8606, centerLng: 2.3376 },
  { id: 'montmartre', name: 'Montmartre', centerLat: 48.8867, centerLng: 2.3431 },
  { id: 'marais', name: 'Le Marais', centerLat: 48.8575, centerLng: 2.3622 },
  { id: 'saint-germain', name: 'Saint-Germain-des-Prés', centerLat: 48.8539, centerLng: 2.3336 },
  { id: 'eiffel-trocadero', name: 'Eiffel-torony / Trocadéro', centerLat: 48.8584, centerLng: 2.2945 },
  { id: 'ile-cite', name: 'Île de la Cité / Île Saint-Louis', centerLat: 48.853, centerLng: 2.3499 },
]

export const mockProgramItems: DestinationCatalog['items'] = [
  {
    id: 'louvre-museum',
    title: 'Louvre múzeum',
    description: 'A világ egyik legnagyobb múzeuma -- Mona Lisa, Milói Vénusz és több ezer más remekmű.',
    category: 'muzeum',
    durationMin: 180,
    energyLevel: 2,
    timeOfDay: ['morning', 'afternoon'],
    indoorOutdoor: 'indoor',
    zoneId: 'louvre-tuileries',
    openingHours: { mon: '09:00-18:00', tue: 'closed', wed: '09:00-21:45', thu: '09:00-18:00', fri: '09:00-21:45', sat: '09:00-18:00', sun: '09:00-18:00' },
    priceRange: '€€',
    bookingRequired: true,
    tags: ['muveszet', 'kultura', 'beltéri'],
    priority: 10,
  },
  {
    id: 'tuileries-walk',
    title: 'Tuileries kert séta',
    description: 'Klasszikus francia kert a Louvre és a Place de la Concorde között.',
    category: 'seta',
    durationMin: 45,
    energyLevel: 1,
    timeOfDay: ['morning', 'afternoon'],
    indoorOutdoor: 'outdoor',
    zoneId: 'louvre-tuileries',
    tags: ['termeszet', 'pihenes'],
    priority: 5,
  },
  {
    id: 'sacre-coeur',
    title: 'Sacré-Cœur bazilika',
    description: 'Montmartre csúcsán álló fehér bazilika, panorámás kilátással Párizsra.',
    category: 'latvanyossag',
    durationMin: 60,
    energyLevel: 2,
    timeOfDay: ['morning', 'afternoon', 'evening'],
    indoorOutdoor: 'mixed',
    zoneId: 'montmartre',
    tags: ['kilatas', 'kultura'],
    priority: 9,
  },
  {
    id: 'montmartre-walk',
    title: 'Montmartre-i művésznegyed séta',
    description: 'Kanyargós utcák, kávézók és utcai festők a Place du Tertre körül.',
    category: 'seta',
    durationMin: 90,
    energyLevel: 2,
    timeOfDay: ['morning', 'afternoon'],
    indoorOutdoor: 'outdoor',
    zoneId: 'montmartre',
    tags: ['muveszet', 'hangulat'],
    priority: 7,
  },
  {
    id: 'marais-food-walk',
    title: 'Marais gasztro séta és sajtkóstoló',
    description: 'Kis sajt- és pékségekbe betérős gasztrotúra a Marais utcáin.',
    category: 'gasztro',
    durationMin: 120,
    energyLevel: 2,
    timeOfDay: ['afternoon', 'evening'],
    indoorOutdoor: 'mixed',
    zoneId: 'marais',
    tags: ['gasztro', 'helyi'],
    priority: 8,
  },
  {
    id: 'place-des-vosges',
    title: 'Place des Vosges',
    description: 'Párizs legrégebbi tervezett tere, szimmetrikus homlokzatokkal és árkádokkal.',
    category: 'latvanyossag',
    durationMin: 30,
    energyLevel: 1,
    timeOfDay: ['morning', 'afternoon', 'evening'],
    indoorOutdoor: 'outdoor',
    zoneId: 'marais',
    tags: ['pihenes', 'fotozas'],
    priority: 4,
  },
  {
    id: 'musee-carnavalet',
    title: 'Musée Carnavalet',
    description: 'Párizs történetét bemutató ingyenes városi múzeum a Marais szívében.',
    category: 'muzeum',
    durationMin: 90,
    energyLevel: 1,
    timeOfDay: ['morning', 'afternoon'],
    indoorOutdoor: 'indoor',
    zoneId: 'marais',
    openingHours: { mon: '10:00-18:00', tue: 'closed', wed: '10:00-18:00', thu: '10:00-18:00', fri: '10:00-18:00', sat: '10:00-18:00', sun: '10:00-18:00' },
    tags: ['kultura', 'beltéri', 'csalad'],
    priority: 6,
  },
  {
    id: 'saint-germain-cafes',
    title: 'Saint-Germain-des-Prés kávéházak',
    description: 'Café de Flore és Les Deux Magots -- irodalmi kávéházi hangulat.',
    category: 'gasztro',
    durationMin: 60,
    energyLevel: 1,
    timeOfDay: ['morning', 'afternoon'],
    indoorOutdoor: 'indoor',
    zoneId: 'saint-germain',
    tags: ['kave', 'hangulat'],
    priority: 5,
  },
  {
    id: 'musee-dorsay',
    title: "Musée d'Orsay",
    description: 'Impresszionista és posztimpresszionista remekművek egy egykori vasútállomáson.',
    category: 'muzeum',
    durationMin: 150,
    energyLevel: 2,
    timeOfDay: ['morning', 'afternoon'],
    indoorOutdoor: 'indoor',
    zoneId: 'saint-germain',
    openingHours: { mon: '09:30-18:00', tue: 'closed', wed: '09:30-18:00', thu: '09:30-21:45', fri: '09:30-18:00', sat: '09:30-18:00', sun: '09:30-18:00' },
    tags: ['muveszet', 'kultura', 'beltéri'],
    priority: 9,
  },
  {
    id: 'luxembourg-garden',
    title: 'Luxembourg-kert',
    description: 'Párizs egyik legszebb parkja, medencével, szobrokkal és árnyas sétányokkal.',
    category: 'seta',
    durationMin: 60,
    energyLevel: 1,
    timeOfDay: ['morning', 'afternoon'],
    indoorOutdoor: 'outdoor',
    zoneId: 'saint-germain',
    tags: ['termeszet', 'pihenes', 'csalad'],
    priority: 6,
  },
  {
    id: 'eiffel-tower',
    title: 'Eiffel-torony felmenetel',
    description: 'Párizs legismertebb látványossága -- kilátás a második emeletről vagy a csúcsról.',
    category: 'latvanyossag',
    durationMin: 120,
    energyLevel: 2,
    timeOfDay: ['afternoon', 'evening'],
    indoorOutdoor: 'mixed',
    zoneId: 'eiffel-trocadero',
    tags: ['kilatas', 'ikon'],
    priority: 10,
  },
  {
    id: 'trocadero-viewpoint',
    title: 'Trocadéro kilátóterasz',
    description: 'A legjobb fotópont az Eiffel-toronyról, különösen napnyugtakor.',
    category: 'latvanyossag',
    durationMin: 30,
    energyLevel: 1,
    timeOfDay: ['afternoon', 'evening'],
    indoorOutdoor: 'outdoor',
    zoneId: 'eiffel-trocadero',
    tags: ['fotozas', 'kilatas'],
    priority: 8,
  },
  {
    id: 'seine-evening-walk',
    title: 'Szajna-parti esti séta',
    description: 'Romantikus séta a folyóparton, a megvilágított hidak alatt.',
    category: 'seta',
    durationMin: 60,
    energyLevel: 1,
    timeOfDay: ['evening'],
    indoorOutdoor: 'outdoor',
    zoneId: 'ile-cite',
    tags: ['romantikus', 'esti'],
    priority: 7,
  },
  {
    id: 'notre-dame-area',
    title: 'Notre-Dame környéke és Île Saint-Louis',
    description: 'A katedrális külseje, majd fagyizás a szomszédos szigeten.',
    category: 'seta',
    durationMin: 75,
    energyLevel: 1,
    timeOfDay: ['morning', 'afternoon', 'evening'],
    indoorOutdoor: 'mixed',
    zoneId: 'ile-cite',
    tags: ['kultura', 'csalad'],
    priority: 7,
  },
  {
    id: 'sainte-chapelle',
    title: 'Sainte-Chapelle',
    description: 'Lenyűgöző gótikus üvegablakok -- az egyik legszebb beltéri élmény Párizsban.',
    category: 'latvanyossag',
    durationMin: 45,
    energyLevel: 1,
    timeOfDay: ['morning', 'afternoon'],
    indoorOutdoor: 'indoor',
    zoneId: 'ile-cite',
    openingHours: { mon: '09:00-17:00', tue: '09:00-17:00', wed: '09:00-17:00', thu: '09:00-17:00', fri: '09:00-17:00', sat: '09:00-17:00', sun: '09:00-17:00' },
    tags: ['muveszet', 'beltéri'],
    priority: 8,
  },
  {
    id: 'seine-boat-tour',
    title: 'Szajna hajókázás (Bateaux-Mouches)',
    description: 'Egyórás hajótúra a folyón, a legfontosabb nevezetességek mellett elhaladva.',
    category: 'latvanyossag',
    durationMin: 60,
    energyLevel: 1,
    timeOfDay: ['afternoon', 'evening'],
    indoorOutdoor: 'outdoor',
    zoneId: 'ile-cite',
    tags: ['kilatas', 'csalad', 'romantikus'],
    priority: 6,
  },
  {
    id: 'marais-bistro-dinner',
    title: 'Vacsora bisztróban a Marais-ban',
    description: 'Hagyományos francia bisztrókonyha egy családi vezetésű étteremben.',
    category: 'gasztro',
    durationMin: 90,
    energyLevel: 1,
    timeOfDay: ['evening'],
    indoorOutdoor: 'indoor',
    zoneId: 'marais',
    openingHours: { mon: '19:00-23:00', tue: '19:00-23:00', wed: '19:00-23:00', thu: '19:00-23:00', fri: '19:00-23:30', sat: '19:00-23:30', sun: 'closed' },
    tags: ['gasztro', 'esti'],
    priority: 7,
  },
  {
    id: 'palais-garnier',
    title: 'Palais Garnier operaház séta',
    description: 'Az Opera épületének díszes előcsarnoka és nézőtere -- vezetett vagy önálló séta.',
    category: 'latvanyossag',
    durationMin: 60,
    energyLevel: 1,
    timeOfDay: ['morning', 'afternoon'],
    indoorOutdoor: 'indoor',
    zoneId: 'louvre-tuileries',
    openingHours: { mon: '10:00-17:00', tue: '10:00-17:00', wed: '10:00-17:00', thu: '10:00-17:00', fri: '10:00-17:00', sat: '10:00-17:00', sun: '10:00-17:00' },
    tags: ['muveszet', 'beltéri'],
    priority: 5,
  },
]

export const mockCatalog: DestinationCatalog = {
  destinationId: mockDestinationId,
  zones: mockZones,
  items: mockProgramItems,
}

export const mockRules: PlannerRules = {
  maxZonesPerDay: 2,
  lunchWindow: { start: '12:00', end: '14:00' },
  dailyEnergyCap: { relaxed: 5, moderate: 7, packed: 10 },
  bufferMinutes: 20,
}
